server:
  port: 8080
  servlet:    context-path: /
spring:  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.19.83.94:3306/db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    #url: jdbc:mysql:///db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password:   thymeleaf:
      prefix: /WEB-INF/pages/
      suffix: .html
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

    
#mybatis-plus配置
mybatis-plus:  type-aliases-package: com.zhxs.sys.entity
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  

logging:
  level: 
    com.zhxs.sys.dao: debug